  # to run this playbook
#   $ ansible-playbook --ask-become srv_config.yml
  # to list tags
#   $ ansible-playbook --list-tags srv_config.yml
  # to run playbook with a specific tag
#   $ ansible-playbook --tags [tag-name] --ask-become srv_config.yml
  # to run this playbook as remote_user oga
#   $ ansible-playbook srv_config.yml

- name: Install Samba package
  tags: samba
  package:
    name: samba
    state: latest

- name: Install unzip
  tags: zip
  package:
    name: unzip
    state: latest

- name: Install OpenTofu
  unarchive:
    src: https://github.com/opentofu/opentofu/releases/download/v1.6.2/tofu_1.6.2_linux_amd64.zip 
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
