---

- hosts: all
  become: true
  tasks:
    
    - name: Install apache2 & php packages
      apt:
        update_cache: yes
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
    
    
    - name: Install apache2 & php packages
      dnf:
        update_cache: yes
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "OracleLinux"
