  # to run this playbook
#   $ ansible-playbook --ask-become srv_config.yml
  # to list tags
#   $ ansible-playbook --list-tags srv_config.yml
  # to run playbook with a specific tag
#   $ ansible-playbook --tags [tag-name] --ask-become srv_config.yml
  # to run this playbook as remote_user oga
#   $ ansible-playbook srv_config.yml
---

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: WorkStations
  become: true
  roles:
    - WorkStations

# All tasks are found in ./roles/assigned_group/tasks/main.yml
# For instance, tasks for web_servers are found in:
#   ./roles/web_servers/tasks/main.yml
