# to run this playbook
#   $ ansible-playbook --ask-become srv_config.yml
# to list tags
#   $ ansible-playbook --list-tags srv_config.yml
# to run playbook with a specific tag
#   $ ansible-playbook --tags [tag-name] --ask-become srv_config.yml
---

- hosts: all
  become: true
  tasks:

- hosts: web_servers
  become: true
  tasks:

    - name: Install apache2 & php packages
      tags: apache,apache2,php,ubuntu
      apt:
        update_cache: yes
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
    
    
    - name: Install apache2 & php packages
      tags: apache,httpd,php,oracleLinux
      dnf:
        update_cache: yes
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "OracleLinux"

- hosts: db_servers
  become: true
  tasks: 

  - name: Install MariaDB package (Oracle Linux)
    tags: db,nmariadb,oracleLinux
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: Install MariaDB package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: Install Samba package
    tags: samba
    package:
      name: samba
      state: latest

- hosts: WorkStations
  become: true
  tasks:

  - name: Install gedit and vim on WorkStations
    tags: gedit,vim,text_editors
    package:
      name:
        - gedit
        - vim
      state: latest
        
