  # to run this playbook
#   $ ansible-playbook --ask-become srv_config.yml
  # to list tags
#   $ ansible-playbook --list-tags srv_config.yml
  # to run playbook with a specific tag
#   $ ansible-playbook --tags [tag-name] --ask-become srv_config.yml
  # to run this playbook as remote_user oga
#   $ ansible-playbook srv_config.yml
---

- name: Install MariaDB package (Oracle Linux)
  tags: db,nmariadb,oracleLinux
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "OracleLinux"

- name: Install MariaDB package (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

